version: "3.7"

services:
  app:
    container_name: interpolations
    image: interpolations:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python run.py
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./:/app
